In [1]:
import tensorflow as tf 
import tensorflow_datasets as tfds
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, MaxPool2D, Flatten
from tensorflow.keras.utils import to_categorical

In [2]:
data, ds_info = tfds.load('iris', split='train[0:80%]', with_info=True)

Shuffling and writing examples to /root/tensorflow_datasets/iris/2.0.0.incompleteH3MROO/iris-train.tfrecord


Dataset iris downloaded and prepared to /root/tensorflow_datasets/iris/2.0.0. Subsequent calls will reuse this data.


In [3]:
for item in data:
    print(item)

{'features': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([5.1, 3.4, 1.5, 0.2], dtype=float32)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>}
{'features': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([7.7, 3. , 6.1, 2.3], dtype=float32)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=2>}
{'features': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([5.7, 2.8, 4.5, 1.3], dtype=float32)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>}
{'features': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.8, 3.2, 5.9, 2.3], dtype=float32)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=2>}
{'features': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([5.2, 3.4, 1.4, 0.2], dtype=float32)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>}
{'features': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([5.6, 2.9, 3.6, 1.3], dtype=float32)>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>}
{'features': <tf.Tensor: shape=(4,), dtype=float32, numpy=

In [4]:
ds_info

tfds.core.DatasetInfo(
    name='iris',
    version=2.0.0,
    description='This is perhaps the best known database to be found in the pattern recognition
literature. Fisher's paper is a classic in the field and is referenced
frequently to this day. (See Duda & Hart, for example.) The data set contains
3 classes of 50 instances each, where each class refers to a type of iris
plant. One class is linearly separable from the other 2; the latter are NOT
linearly separable from each other.',
    homepage='https://archive.ics.uci.edu/ml/datasets/iris',
    features=FeaturesDict({
        'features': Tensor(shape=(4,), dtype=tf.float32),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=3),
    }),
    total_num_examples=150,
    splits={
        'train': 150,
    },
    supervised_keys=('features', 'label'),
    citation="""@misc{Dua:2019 ,
    author = "Dua, Dheeru and Graff, Casey",
    year = "2017",
    title = "{UCI} Machine Learning Repository",
    url = "http://archiv

In [9]:
num_class = 3

def preprocess(features):

  f = features['features']
  l = features['label']
  f = tf.cast(features['features'], tf.float32) / 255. 
  l = tf.one_hot(l, depth=num_class)

  return f, l

def solution_model():

  train_dataset = data.map(preprocess).batch(10)

  #for item in train_dataset:
    #print(item[0])

  model = Sequential()
  model.add(Flatten(input_shape=(4, 1)))
  model.add(Dense(256, activation='relu'))
  model.add(Dense(64, activation='relu'))
  model.add(Dense(num_class, activation='softmax'))

  model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

  model.fit(train_dataset, epochs=10, verbose=1)

  return model

In [10]:
model = solution_model()

Epoch 1/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0984 - accuracy: 0.4536
Epoch 2/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0960 - accuracy: 0.4361
Epoch 3/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0938 - accuracy: 0.4790
Epoch 4/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0908 - accuracy: 0.6666
Epoch 5/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0865 - accuracy: 0.6838
Epoch 6/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0806 - accuracy: 0.6838
Epoch 7/10
12/12 [==============================] - 0s 2ms/step - loss: 1.0729 - accuracy: 0.6838
Epoch 8/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0611 - accuracy: 0.6874
Epoch 9/10
12/12 [==============================] - 0s 3ms/step - loss: 1.0464 - accuracy: 0.6838
Epoch 10/10
12/12 [==============================] - 0s 2ms/step - loss: 1.0272 - accuracy: 0.6874
